# Generated by Django 3.2.12 on 2022-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movies", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=5, unique=True)),
            ],
            options={"verbose_name_plural": "countries"},
        ),
        migrations.AlterModelOptions(name="cast", options={}),
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"}
        ),
        migrations.AlterModelOptions(
            name="collection", options={"verbose_name_plural": "Collections"}
        ),
        migrations.AlterModelOptions(
            name="comment", options={"verbose_name_plural": "Comments"}
        ),
        migrations.AlterModelOptions(
            name="movie", options={"verbose_name_plural": "Movies"}
        ),
        migrations.AlterModelOptions(
            name="rating", options={"verbose_name_plural": "Ratings"}
        ),
        migrations.AlterModelOptions(
            name="vote", options={"verbose_name_plural": "Votes"}
        ),
        migrations.RemoveField(model_name="movie", name="country"),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.ManyToManyField(to="movies.Country"),
        ),
    ]
