# Generated by Django 3.2.12 on 2022-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movies", "0002_auto_20220608_2321")]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_id",
            field=models.CharField(
                blank=True,
                help_text="Movie trailer ID",
                max_length=20,
                null=True,
                unique=True,
            ),
        )
    ]
