# Generated by Django 3.2.12 on 2022-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movies", "0003_movie_trailer_id")]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="background",
            field=models.URLField(
                blank=True,
                help_text="Collection photo",
                max_length=220,
                null=True,
                verbose_name="Collection photo",
            ),
        )
    ]
