# Generated by Django 4.0.6 on 2022-07-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("movies", "0004_collection_background")]

    operations = [
        migrations.AlterUniqueTogether(
            name="streamingplatform", unique_together={("service", "movie")}
        )
    ]
