# Generated by Django 4.1.4 on 2023-02-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movies", "0006_alter_movie_plot")]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="full_name",
            field=models.CharField(
                help_text="Cast member name",
                max_length=150,
                verbose_name="Cast member name",
            ),
        )
    ]
