# Generated by Django 4.1.6 on 2023-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_alter_movie_actors_alter_movie_directors_and_more")
    ]

    operations = [
        migrations.RenameModel(old_name="Category", new_name="Genre"),
        migrations.RemoveField(model_name="genre", name="parent"),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
        migrations.RenameField(
            model_name="movie", old_name="country", new_name="countries"
        ),
        migrations.RenameField(
            model_name="movie", old_name="categories", new_name="genres"
        ),
    ]
