# Generated by Django 4.1.6 on 2023-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("movies", "0009_rename_category_model_and_country_field")]

    operations = [
        migrations.AlterModelOptions(
            name="genre", options={"verbose_name_plural": "Genres"}
        ),
        migrations.RemoveField(model_name="genre", name="level"),
        migrations.RemoveField(model_name="genre", name="lft"),
        migrations.RemoveField(model_name="genre", name="rght"),
        migrations.RemoveField(model_name="genre", name="tree_id"),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Genre name", max_length=150, verbose_name="Genre name"
            ),
        ),
    ]
